# SPDX-License-Identifier: Apache-2.0

name: Run Examples
description: Run vaccel examples

inputs:
  # ignored
  prefix:
    default: ${{ github.workspace }}/opt
  # ignored
  valgrind:
    default: 'false'
  # ignored
  package:
    default: 'vaccel'

runs:
  using: composite
  steps:
    - name: Ensure run dir exists
      run: |
        uid=$(id -u)
        run_dir="/run/user/${uid}"

        if [[ -d "$run_dir" ]]; then
          exit 0
        fi

        sudo mkdir -p "$run_dir"
        sudo chown -R  "$uid" "$run_dir"
      shell: bash

    - name: Run examples
      run: python3 run-examples.py
      shell: bash
