name: Run Tests
description: Run project tests and generate coverage report

inputs:
  build-path:
    default: 'build'
  source-path:
    default: '.'
  # ignored
  valgrind:
    default: 'false'
  coverage:
    default: 'false'
  # ignored
  gcov:
    default: 'gcov'

runs:
  using: composite
  steps:
    - name: Install dependencies
      working-directory: ${{ inputs.source-path }}
      run: |
        # Use pre-meson NumPy so our arm jammy runners will work correctly
        pip install "numpy<1.25"

        arch=$(python3 -c "import platform; print(platform.architecture()[0])")
        if [[ "${arch}" == "32bit" ]]; then
          pip install .[test]
        else
          pip install .[test-full]
        fi
      shell: bash

    - name: Run tests
      working-directory: ${{ inputs.source-path }}
      run: python3 -m pytest
      shell: bash

    - name: Calculate coverage
      working-directory: ${{ inputs.source-path }}
      if: inputs.coverage == 'true'
      env:
        BUILD_PATH: ${{ inputs.build-path }}
      run: |
        pip install tomli
        pkg_name=$(python3 -c \
          "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['name'])")
        python3 -m pytest \
          --cov-report term \
          --cov-report xml:"${BUILD_PATH}/coverage.xml" \
          --cov="$pkg_name" tests/
      shell: bash
