name: Generate API Reference

on:
  workflow_call:
    inputs:
      actions-repo:
        type: string
        default: 'nubificus/vaccel'
      actions-ref:
        type: string
        default: 'main'
      deploy:
        type: boolean
        default: false
      target-repo-owner:
        type: string
        default: 'nubificus'
      target-repo-name:
        type: string
        default: 'vaccel-docs'
      target-workflow:
        type: string
        default: 'dispatch-update-external-repo.yml'
    secrets:
      VACCEL_BOT_PRIVATE_KEY:
        required: true

permissions: read-all

jobs:
  generate-reference:
    name: Generate API Reference
    runs-on: base-dind-2204-amd64
    steps:
      - name: Parse repository names
        id: parse-repos
        env:
          ACTIONS_REPO: ${{ inputs.actions-repo }}
        run: |
          {
            echo "repo-name=$(basename "$GITHUB_REPOSITORY")"
            echo "actions-repo-name=$(basename "$ACTIONS_REPO")"
          } >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Generate initialization vaccel-bot token
        id: generate-init-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          repositories: |
            ${{ steps.parse-repos.outputs.repo-name }}
            ${{ steps.parse-repos.outputs.actions-repo-name }}
          permission-contents: read

      - name: Checkout .github directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-ref }}
          token: ${{ steps.generate-init-token.outputs.token }}

      - name: Initialize workspace
        id: initialize-workspace
        uses: ./.github/actions/initialize-workspace
        with:
          remote-actions-repo: ${{ inputs.actions-repo }}
          fetch-depth: 0
          submodules: 'false'
          token: ${{ steps.generate-init-token.outputs.token }}

      - name: Determine SHA and branch
        id: get-revision
        uses: ./.github/actions/get-revision-info

      - name: Generate trigger vaccel-bot token
        id: generate-trigger-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          owner: ${{ inputs.target-repo-owner }}
          repositories: ${{ inputs.target-repo-name }}
          permission-actions: write

      - name: Trigger docs update
        id: trigger-update
        uses: the-actions-org/workflow-dispatch@v4
        env:
          RUN_NAME: >-
            Update External Repo ${{ github.repository }}
            [Run ID: ${{ github.run_id }}]
        with:
          workflow: ${{ inputs.target-workflow }}
          ref: main
          repo: >-
            ${{ format('{0}/{1}',
              inputs.target-repo-owner, inputs.target-repo-name) }}
          token: ${{ steps.generate-trigger-token.outputs.token }}
          run-name: ${{ env.RUN_NAME }}
          inputs: >-
            {
              "run-name": "${{ env.RUN_NAME }}",
              "trigger-id": "${{ github.run_id }}",
              "ref": "${{ steps.get-revision.outputs.sha }}",
              "branch": "${{ steps.get-revision.outputs.branch }}",
              "repo": "${{ github.repository }}",
              "deploy": "${{ inputs.deploy }}"
            }
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m
          wait-for-completion-interval: 30s
          wait-for-completion-timeout: 20m
          workflow-logs: json-output

      - name: Print remote request info
        env:
          REMOTE_REPO: >-
            ${{ format('{0}/{1}',
              inputs.target-repo-owner, inputs.target-repo-name) }}
          REMOTE_ID: ${{ steps.trigger-update.outputs.workflow-id }}
          REMOTE_URL: ${{ steps.trigger-update.outputs.workflow-url }}
          DEPLOY: ${{ inputs.deploy }}
        run: |
          echo "## Remote request info" >> "$GITHUB_STEP_SUMMARY"
          echo "- Triggered **${REMOTE_REPO}** run [#${REMOTE_ID}](${REMOTE_URL})" \
            >> "$GITHUB_STEP_SUMMARY"

          [[ "$DEPLOY" == 'true' ]] || exit 0

          logs=$(cat <<'EOF'
          ${{ steps.trigger-update.outputs.workflow-logs }}
          EOF
          )
          pr_number=$(
            echo "$logs" | jq -r '
              .["Update Repo / Verify Build"]
              | map(select(
                  .message != null
                  and (.message | test("Pull request number"))
                ))
              | map(.message | capture("Pull request number: (?<val>[^\\s]+)").val)
              | .[1]
            '
          )
          pr_operation=$(
            echo "$logs" | jq -r '
              .["Update Repo / Verify Build"]
              | map(select(
                  .message != null
                  and (.message | test("Pull request operation"))
                ))
              | map(.message | capture("Pull request operation: (?<val>[^\\s]+)").val)
              | .[1]
            '
          )
          pr_url=$(
            echo "$logs" | jq -r '
              .["Update Repo / Verify Build"]
              | map(select(
                  .message != null
                  and (.message | test("Pull request URL"))
                ))
              | map(.message | capture("Pull request URL: (?<val>[^\\s]+)").val)
              | .[1]
            '
          )
          echo ""
          echo "${pr_operation^} PR: ${pr_url}"
          echo "- ${pr_operation^} PR [${REMOTE_REPO}#${pr_number}](${pr_url})" \
            >> "$GITHUB_STEP_SUMMARY"
