name: Generate docs

on:
  push:
    branches: [ "main", "feat_cleanup_vectorops"]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: gntouts/vacceldoc:0.1.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate docs
        env:
          VACCEL_BACKENDS: /usr/local/lib/libvaccel-noop.so
          LD_LIBRARY_PATH: /usr/local/lib
          PYTHONPATH: .
        run: |
          /bin/bash _docs/autogen.sh
      - name: Verify generation
        run: |
          ls _docs/docs
      
      # FIXME: add text manipulation steps (?)
      - name: Format generated docs
        shell: bash
        run: |
          echo "Removing <kbd> tags"
          sed -i 's/<kbd>//g' _docs/docs/*.md
          sed -i 's/<\/kbd>//g' _docs/docs/*.md
          echo "Removing lazydocs watermark"
          sed -i "s/_This file was automatically generated via \[lazydocs\]//g" _docs/docs/*.md
          sed -i "s/(https:\/\/github.com\/ml-tooling\/lazydocs)._//g" _docs/docs/*.md
      # FIXME: push to vaccel-docs
      - name: Push to vaccel-docs
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.NBFC_BUILDER_TOKEN }}
        with:
          source_folder: '_docs/docs'
          destination_repo: 'nubificus/vaccel-docs'
          destination_folder: 'docs/python'
          user_email: 'ananos@nubificus.co.uk'
          user_name: 'ananos'
          commit_msg: '[GHA] Update the doc files for the Python API.'
          destination_branch: 'feat_update_release'

# TODO:
# Verify last step works
# Add overview-file (lazydocs)
# Add src-base-url (lazydocs)
# Add version (lazydocs)