name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-dist:
    name: Build and Upload
    uses: nubificus/vaccel/.github/workflows/verify-build.yml@main
    with:
      release: true
      package: 'python'
      options: ''
      upload-subpath: 'python'
    secrets: inherit

  generate-api-reference:
    name: Generate API Reference
    uses: ./.github/workflows/generate-api-reference.yml
    with:
      deploy: true
    secrets: inherit


