name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  build-dist:
    name: Build and Upload
    uses: nubificus/vaccel/.github/workflows/verify-build.yml@main
    with:
      release: true
      package: 'python'
      options: ''
      upload-subpath: 'python'
    secrets: inherit

  generate-api-reference:
    name: Generate API Reference
    uses: ./.github/workflows/generate-api-reference.yml
    with:
      deploy: true
    secrets: inherit

  update-release:
    needs: [build-dist, generate-api-reference]
    name: Update Release
    if: always()
    uses: nubificus/vaccel/.github/workflows/update-release.yml@main
    with:
      artifacts-path: 'python'
      result: >-
        ${{ needs.build-dist.result != 'failure' &&
          needs.generate-api-reference.result != 'failure' &&
          'success' || 'failure' }}
    secrets: inherit
